#!/bin/sh
#
# Set boot.log permissions so only root can access application password
# Copyright 2015 Bitnami.com All Rights Reserved
#

. /opt/bitnami/scripts/init/functions

chmod 0600 /var/log/boot.log
