#!/bin/sh
# 
# Configures a random account password for FTP conections
# Copyright 2015 Bitnami.com All Rights Reserved
#

if [ -f "/root/changepass" ] ; then 
  pwgen -s -1 50 > /root/pass
fi
if [ "x$1" != "x" ]; then
  echo "$1" > /root/pass
fi

if [ -f /root/pass ]; then 
  head -1 /root/pass >> /root/pass
  head -2 /root/pass | passwd bitnamiftp 2> /dev/null 1>&2
  for f in `find /opt/bitnami/apps/ -regex '.*\/\(updateip\|bnconfig\)' -type f -executable` ; do
    $f --ftp_password `head -1 /root/pass` 2> /dev/null 1>&2
  done
  rm -rf /root/pass
  rm -rf /root/changepass
fi
